
global:
  scrape_interval: 5m
  scrape_timeout: 2m

scrape_configs:
  # Pruebas iperf3
  - job_name: 'iperf3-probe-1'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 172.18.0.102:5201
    params:
      puerto: ['5201']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instancia
      - target_label: __address__
        replacement: 172.18.0.101:9579

  - job_name: 'iperf3-probe-2'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 172.18.0.102:5201
    params:
      puerto: ['5201']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instancia
      - target_label: __address__
        replacement: 172.18.0.101:9579

  # Pruebas de velocidad
  - job_name: 'speedtest-probe-1'
    metrics_path: /probe
    static_configs:
      - targets:
          - 172.18.0.106:9516

  - job_name: 'speedtest-probe-2'
    metrics_path: /probe
    static_configs:
      - targets:
          - 172.18.0.106:9516

